version: "3.8"
services:
  frp-server:
    container_name: "frp-server"
    image: snowdreamtech/frps
    environment:
      TZ: Asia/Shanghai
    network_mode: "host"
    volumes:
      - ./frps.ini:/etc/frp/frps.ini
    restart: always
