version: '3.1'

services:
   phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - db
    ports:
      - 8089:80
    environment:
      - PMA_ARBITRARY=1
networks:
  db:
    external: true