version: '3.3'

services:
  traefik:
    image: traefik:v2.4.8
    container_name: 'traefik'
    restart: always
    networks: 
      - traefik
    environment:
      ALICLOUD_ACCESS_KEY: ALICLOUD_ACCESS_KEY
      ALICLOUD_SECRET_KEY: ALICLOUD_SECRET_KEY 
      TZ: Asia/Shanghai
    command: 
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.network=traefik"  
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.default.acme.email=891841484@qq.com"
      - "--certificatesresolvers.default.acme.storage=/etc/traefik/acme.json"
      - "--certificatesresolvers.default.acme.dnschallenge=true"
      - "--certificatesresolvers.default.acme.dnschallenge.provider=alidns"
      - "--providers.file.filename=/etc/traefik/traefik-dynamic.toml"
      - "--providers.file.watch=true"
      - "--log.level=TRACE"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/:/etc/traefik/
networks:
  traefik:
    external: true
